#!/bin/sh

# Author; gitneeraj

# import colors for dwm
source "$(dirname "$0")/colors"

dwm_cpu_temp () {
    # RAM memory used percentage
    CPUTEMP=$(sed 's/000$/°C/' /sys/class/thermal/thermal_zone0/temp | tr -d '°C')
    SUFFIX="°C"

    if [ $CPUTEMP -le 20 ]; then
        echo -e "$SEP1" "$GREEN $NC""$CPUTEMP""$SUFFIX" "$SEP2"
    elif [ $CPUTEMP -gt 20 -a $CPUTEMP -le 30 ]; then
        echo -e "$SEP1" "$LIGHTGREEN $NC""$CPUTEMP""$SUFFIX" "$SEP2"
    elif [ $CPUTEMP -gt 30 -a $CPUTEMP -le 60 ]; then
        echo -e "$SEP1" "$YELLOW $NC""$CPUTEMP""$SUFFIX" "$SEP2"
    elif [ $CPUTEMP -gt 60 -a $CPUTEMP -le 80 ]; then
        echo -e "$SEP1" "$ORANGE $NC""$CPUTEMP""$SUFFIX" "$SEP2"
    else
        echo -e "$SEP1" "$RED $NC""$CPUTEMP""$SUFFIX" "$SEP2"
    fi
}

dwm_cpu_temp