#!/bin/sh

# A dwm_bar function that shows the current date and time
# Joe Standring <git@joestandring.com>
# GNU GPLv3

# Date is formatted like like this: "[Mon 01-01-00 00:00:00]"
dwm_date () {
    NC="\x01"
    RED="\x05"
    ORANGE="\x06"
    YELLOW="\x07"
    LIGHTGREEN="\x08"
    GREEN="\x09"

    # printf "%s" "$SEP1"
    # # printf "📆 %s" "$(date "+%a %d-%m-%y %T")"
    # printf " %s" "$(date "+%a %d %b %Y, %I:%M %p")"
    # printf "%s\n" "$SEP2"
    TODAY=$(date "+%a %d %b %Y, %I:%M %p")
    echo -e "$SEP1" "$GREEN $NC""$TODAY" "$SEP2"
}

dwm_date
