#!/bin/sh

# Author: gitneeraj
# Dependencies: pulseaudio, pamixer, dunst


CHANGE=${1}

# Detect the Channel that has active audio running. Useful when bluetooth headsets are connected
PLAYING_CHANNEL=$(pactl list short sinks | grep -Ei 'RUNNING' | awk '{ print $1 }')

[[ -z $PLAYING_CHANNEL ]] && CHANNEL="0" || CHANNEL=$PLAYING_CHANNEL

if [ "$CHANGE" = "mute" ]; then
    pactl set-sink-mute ${CHANNEL} toggle
    # amixer set Master toggle
else
    pactl set-sink-volume ${CHANNEL} ${CHANGE}10%
    # amixer set Master playback 2${CHANGE}
fi

VOL=$(pamixer --get-volume-human | tr -d '%')
# VOL=$(awk -F"[][]" '/dB/ { print $2 }' <(amixer sget Master))
TEXT="level at ${VOL}%"

if [ "$VOL" = "muted" ] || [ "$VOL" -eq 0 ]; then
    TEXT="muted"
    APPNAME="sound_volume_mute"
elif [ "$VOL" -gt 0 ] && [ "$VOL" -le 33 ]; then
    APPNAME="sound_volume_low"
elif [ "$VOL" -gt 33 ] && [ "$VOL" -le 66 ]; then
    APPNAME="sound_volume_medium"
else
    APPNAME="sound_volume_high"
fi

dunstify -u normal -a ${APPNAME} -r 11 "Volume ${TEXT}"